# This file is auto-generated by the `evennia connections` wizard.
# Don't edit manually, your changes will be overwritten.

GAME_INDEX_ENABLED = True
GAME_INDEX_LISTING = \
{   'game_status': 'launched',
    'game_website': 'https://demo.evennia.com',
    'listing_contact': 'a@a.com',
    'long_description': 'The Evennia demo server shows off a standard install '
                        'of [Evennia](http://www.evennia.com), with a '
                        'single-player tutorial world as well as '
                        'the *Evscaperoom* - a full story-rich escaperoom-style game!\n\n'
                        'People can play around as builders and '
                        'explore some of Evennia\'s functionality. You can also chat '
                        'to developers in the Evennia IRC channel directly from '
                        'the demo!\n\nMax idle time is seven days and the demo '
                        'may be reset without notice, at which point you '
                        'need to recreate your account.',
    'short_description': 'The Evennia demo server',
    'telnet_hostname': 'demo.evennia.com',
    'telnet_port': '4000',
    'web_client_url': 'https://demo.evennia.com/webclient'}
